In [ ]:
#Model evaluation and selection
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

#load data set
iris=load_iris()
X,y=iris.data,iris.target

In [ ]:
#split into train and test set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#initialize models
models={
    "Logistic Regression":LogisticRegression(max_iter=200),
    "Support Vector Machine":SVC(),
    "K-Nearest Neighbors":KNeighborsClassifier()
}

#evaluate each model
for name,model in models.items():
    #cross-validatoin score
    cv_score=cross_val_score(model,X_train,y_train,cv=5)
    #train and predict
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    #metrics
    acc=accuracy_score(y_test,y_pred)
    print(f"\nModel:{name}")
    print(f"Cross-validation Accuracy:{cv_score.mean():2f}")
    print(f"Test Accuracy:{acc:.2f}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test,y_pred))
print("Classification Report:")
print(classification_report(y_test,y_pred))    


Model:Logistic Regression
Cross-validation Accuracy:0.966667
Test Accuracy:1.00
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:

Model:Support Vector Machine
Cross-validation Accuracy:0.950000
Test Accuracy:1.00
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:

Model:K-Nearest Neighbors
Cross-validation Accuracy:0.941667
Test Accuracy:1.00
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

